### PR TITLE
Add UMD'd distributable builds with Browserify

### PR DESCRIPTION
**Pull request by stewart**
Adds single-file distributable builds (one minified, one not) using Browserify + UglifyJS. These can live in-repo, and will not be pushed as part of the NPM module.

### CODE REVIEW

**Comment by deadprogram** [comment]
Looks good. One question I have, should we be doing a dist as part of the `make release` process, to make sure the dist version is same as any npm version?

**Comment by stewart** [comment]
This seems possible, but probably slightly tricker to implement. There's probably enough going on in the `release` make task that we should split it out into `scripts/release` or something.

**Comment by deadprogram** [comment]
@stewart does this branch still apply?

**Comment by edgarsilva** [comment]
@stewart closing this as per your comments yesterday.

**Pull request closed without merging**
